theme: jekyll-theme-minimal
title: SporosDAO
description: Sweat equity management for web3 builders
logo: https://user-images.githubusercontent.com/2234901/168681236-150b47ef-85c6-4ef7-ba8a-3a090a1acec8.png
